### ISSUE TITLE
Memory leak in forcedphotrunner.py

### ISSUE THREAD

**Issue by genghisken** [lukeshingles/atlasserver#12]
I had to restart the forcedphotrunner.py process.  It has a severe memory leak.  psweb had run out of memory.

```
2021-01-31 12:10:29.471522  Waiting for tasks...
2021-01-31 12:31:29.034016  Unfinished jobs in queue: 1
2021-01-31 12:31:29.045658  job07743: Starting job for ken.smith (who has run 0 tasks in this pass so far):
2021-01-31 12:31:29.045763  job07743: {'id': 7743, 'timestamp': datetime.datetime(2021, 1, 31, 12, 31, 28, 794188), 'ra': 149.25245, 'dec': -10.34936, 'mjd_min': 59215.0, 'mjd_max': None, 'use
r_id': 1, 'use_reduced': 0, 'comment': '', 'finishtimestamp': None, 'send_email': 0, 'starttimestamp': None, 'email': 'k.w.smith@qub.ac.uk', 'username': 'ken.smith'}
2021-01-31 12:31:29.046075  job07743: Executing on atlas: nice -n 19 /atlas/bin/force.sh 149.25245 -10.34936 m0=59215.0 dodb=1 parallel=16 | sort -n | tee ~/atlasserver/results/job07743.txt
Traceback (most recent call last):
  File "forcephotrunner.py", line 447, in <module>
    main()
  File "forcephotrunner.py", line 436, in main
    queuedtaskcount = do_taskloop()
  File "forcephotrunner.py", line 340, in do_taskloop
    localresultfile = runforced(conn=conn, logprefix=logprefix, task=task)
  File "forcephotrunner.py", line 106, in runforced
    encoding='utf-8', bufsize=1, universal_newlines=True)
  File "/usr/local/swtools/python/atls/anaconda3/envs/forced37/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/swtools/python/atls/anaconda3/envs/forced37/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```
In the meantime, while investigating, we should restart the process at least weekly.

**Comment by lukeshingles** [comment]
Thanks, Ken. I would have expected the start_forcedphotrunner.sh script to restart the Python script after an error like this. Was that not the case?

I've reverted to running the plotting script in a separate process. Let's see if that keeps the memory usage from growing.

**Comment by lukeshingles** [comment]
@genghisken could please check if this issue is now solved?

**Comment by lukeshingles** [comment]
@genghisken looks like this is now solved, so I'll close this issue soon. Let me know if this is not the case.
